name: sahay_loan_app
description: "SAHAY - Your Trusted Loan Partner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^17.0.0

  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0

  # Image picker — for OCR camera/gallery
  image_picker: ^1.0.7

  # File picker — for documents (PDF, images)
  file_picker: ^8.0.0+1

  # Image to base64 conversion
  image: ^4.1.7

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.66.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  confetti: ^0.7.0

  # State Management
  provider: ^6.1.2

  # Shared preferences — store token locally
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0

  # Payment
  flutter_stripe: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/